name: Robert Walls 
url: http://tips.walls.ninja

exclude: [bibble, README.md, Makefile, CNAME]

# use this library to parse Markdown
markdown: redcarpet
redcarpet:
    extensions: [smart, tables]

# colorize code snippets with the pygments module
pygments: true

# The path structure for blog posts.
permalink: /:title.html

# Sections on the "people" page.
roles:
    - {key: faculty, name: Faculty}
    - {key: staff, name: Staff}
    - {key: postdoc, name: Researchers}
    - {key: grad, name: Graduate Students}
    - {key: collab, name: Collaborators}
    - {key: alum, name: Alumni}

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: 'http://tips.walls.ninja'

# Navigation bar links.
#navigation:
#    - title: Home
#      link: /
#    - title: People
#      link: /people.html
#    - title: Research
#      link: /research/
#    - title: Publications
#      link: /publications.html
#    - title: Code
#      link: /code.html
